# Generated by Django 3.2.1 on 2024-05-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=64, null=True)),
                ('region', models.CharField(blank=True, choices=[('Upper West Region', 'Upper West Region'), ('Upper East Region', 'Upper East Region'), ('North East Region', 'North East Region'), ('Northern Region', 'Northern Region'), ('Savannah Region', 'Savannah Region'), ('Bono East Region', 'Bono East Region'), ('Brong Ahafo Region', 'Brong Ahafo Region'), ('Oti Region', 'Oti Region'), ('Volta Region', 'Volta Region'), ('Eastern Region', 'Eastern Region'), ('Ashanti Region', 'Ashanti Region'), ('Ahafo Region', 'Ahafo Region'), ('Western North Region', 'Western North Region'), ('Western Region', 'Western Region'), ('Central Region', 'Central Region'), ('Greater Accra Region', 'Greater Accra Region')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
