# Generated by Django 3.2.1 on 2024-05-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('mother', 'Mother')], default='admin', max_length=13),
            preserve_default=False,
        ),
    ]
