# Generated by Django 3.2.1 on 2024-09-13 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20240913_0744'),
        ('account', '0002_auto_20240518_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_users', to='base.hospital'),
        ),
    ]
