# Generated by Django 3.2.1 on 2024-09-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('mother', 'Mother'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('other', 'Other')], max_length=13),
        ),
    ]
