# Generated by Django 3.2.1 on 2024-09-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='0551878701', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
