# Generated by Django 3.2.1 on 2024-06-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20240523_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='rating',
        ),
    ]
