# Generated by Django 3.2.1 on 2024-09-14 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_auto_20240913_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinaton',
            name='child',
        ),
        migrations.AddField(
            model_name='vaccinaton',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
            preserve_default=False,
        ),
    ]
