# Generated by Django 3.2.1 on 2024-09-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20240914_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='child',
        ),
    ]
