# Generated by Django 3.2.1 on 2024-09-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=9),
        ),
    ]
